@extends('layouts.telaPlay')
@section('disci', 'Química')
@section('tempo', '/img/timer_quimica.gif')
@section('dificuty', 'Dificil')
@section('questText', 'Quanto é 1 + 1?')
@section('resp1', '5')
@section('resp2', '6')
@section('resp3', '2')
@section('resp4', '4')
